/**
 * FILE: app/share/[token]/page.tsx
 *
 * WHAT THIS DOES:
 *   Public read-only report page. No auth required. Fetches report JSON
 *   via GET /api/reports/share?token=<uuid> and renders a clean summary.
 *   Shared links show the period summary without any sensitive nav or store config.
 *
 * CHANGES THIS SESSION:
 *   - Initial creation for Phase 7 report sharing
 *
 * WHERE IT FITS:
 *   Outside the (dashboard) route group — no session guard, no nav.
 *   Accessible by anyone with the link.
 *
 * CALLED BY / IMPORTS FROM:
 *   Share link sent by merchant
 */
import { notFound } from 'next/navigation'
import { createSupabaseServiceClient } from '@/lib/supabase/server'
import type { PeriodReport } from '@/types'

function fmt(n: number): string {
  if (Math.abs(n) >= 100000) return `₹${(n / 100000).toFixed(1)}L`
  if (Math.abs(n) >= 1000) return `₹${(n / 1000).toFixed(1)}K`
  return `₹${n.toLocaleString('en-IN')}`
}

interface Props { params: { token: string } }

export default async function SharePage({ params }: Props) {
  const svc = createSupabaseServiceClient()

  const { data, error } = await svc
    .from('periodic_reports')
    .select('report_json, report_type, period_start, period_end, store_id')
    .eq('share_token', params.token)
    .maybeSingle()

  if (error || !data) notFound()

  const report = data.report_json as PeriodReport
  const { data: store } = await svc
    .from('stores')
    .select('name')
    .eq('id', data.store_id)
    .maybeSingle()

  const profitColor = report.netProfit >= 0 ? 'text-green-700' : 'text-red-600'

  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4">
      <div className="max-w-lg mx-auto space-y-5">
        {/* Header */}
        <div>
          <h1 className="text-xl font-bold text-gray-900">{store?.name ?? 'Store'}</h1>
          <p className="text-sm text-gray-500 mt-0.5">
            {report.periodLabel} · {report.transactionCount} transactions
          </p>
        </div>

        {/* Summary cards */}
        <div className="grid grid-cols-2 gap-3">
          {[
            { label: 'Total sales',     value: fmt(report.sales),     accent: '' },
            { label: 'Total purchases', value: fmt(report.purchases),  accent: '' },
            { label: 'Net profit',      value: fmt(report.netProfit), accent: profitColor },
            { label: 'GST payable',     value: fmt(report.taxSummary.payable), accent: '' },
          ].map(({ label, value, accent }) => (
            <div key={label} className="bg-white rounded-xl border border-gray-200 p-4">
              <p className="text-xs text-gray-500 uppercase tracking-wide mb-1">{label}</p>
              <p className={`text-xl font-bold ${accent || 'text-gray-900'}`}>{value}</p>
            </div>
          ))}
        </div>

        {/* Top products */}
        {report.topProducts.length > 0 && (
          <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
            <div className="px-4 py-3 border-b border-gray-100">
              <p className="text-sm font-semibold text-gray-900">Top products</p>
            </div>
            {report.topProducts.slice(0, 5).map((p) => (
              <div key={p.productId} className="flex items-center justify-between px-4 py-3 border-b border-gray-50 last:border-0">
                <p className="text-sm text-gray-900 truncate flex-1 mr-4">{p.productName}</p>
                <p className="text-sm font-semibold text-gray-700 shrink-0">{fmt(p.revenue)}</p>
              </div>
            ))}
          </div>
        )}

        {/* GST breakdown */}
        <div className="bg-white rounded-xl border border-gray-200 p-4 space-y-3">
          <p className="text-sm font-semibold text-gray-900">GST summary</p>
          {[
            ['Collected on sales',  fmt(report.taxSummary.collected)],
            ['Paid on purchases',   fmt(report.taxSummary.paid)],
            ['Net payable',         fmt(report.taxSummary.payable)],
          ].map(([label, value]) => (
            <div key={label} className="flex justify-between text-sm">
              <span className="text-gray-500">{label}</span>
              <span className="font-medium text-gray-900">{value}</span>
            </div>
          ))}
        </div>

        {/* Footer */}
        <p className="text-xs text-gray-400 text-center pb-4">
          Generated by PakkaHisab · This link is read-only and shareable
        </p>
      </div>
    </div>
  )
}
